version: '3'
services:
  bot:
    image: node:16-alpine
    volumes:
      - .:/mnt
    working_dir: /mnt
    env_file:
      - discord.env
    entrypoint: sh -c 'yarn install && yarn start'
    restart: always
